### ISSUE TITLE
Hass Diagnostic leads to errors in YaHa cloud notifier in 2024.5

### ISSUE THREAD

**Issue by artt652** [AlexxIT/HassDiagnostics#3]
Hass Diagnostic leads to errors in YaHa cloud notifier in 2024.5
https://github.com/dext0r/yandex_smart_home/issues/530

### Эта ошибка возникла в пользовательской интеграции.
 ```
Регистратор: homeassistant
Источник: custom_components/yandex_smart_home/notifier.py:288
интеграция: Yandex Smart Home (документация, проблемы)
Первое сообщение: 23:28:02 (192 сообщений)
Последнее сообщение: 23:32:24
 
Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/yandex_smart_home/notifier.py", line 288, in _state_change_listener
    await asyncio.gather(*[n.async_event_handler(event) for n in hass.data[DOMAIN][NOTIFIERS]])
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 831, in gather
    fut = ensure_future(arg, loop=loop)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/tasks.py", line 693, in ensure_future
    loop = events.get_event_loop()
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/asyncio/events.py", line 702, in get_event_loop
    raise RuntimeError('There is no current event loop in thread %r.'
RuntimeError: There is no current event loop in thread 'ImportExecutor_0'.
```

**Comment by AlexxIT** [comment]
https://github.com/AlexxIT/HassDiagnostics/releases/tag/v1.1.0
